Theme darkwolfbootstrap for phpMyAdmin 5.2
phpmyadmin/themes pull request #82
Opened 2022-08-23 18:25 UTC by SteppenWolf68

I would add the verification of this theme and have the possibility that it can be downloaded from https://www.phpmyadmin.net/themes/

Thank you very much

[darkwolfbootstrap.zip](https://github.com/phpmyadmin/themes/files/9409651/darkwolfbootstrap.zip)

2022-08-23 18:45 UTC, williamdes commented
I am thinking about re-working our theme process to only have to upload scss files and a CI job would build the CSS files
By the way, do you use and edit scss files?
And also write some indications for users to be able to test and write new themes

2022-08-23 19:01 UTC, SteppenWolf68 commented
Hi @williamdes ....Thanks for answering.

I've edited a bit of SCSS, I'm not very familiar with it, but I think it's just a matter of studying to expand knowledge.
We have to be updated as much as possible or we will be stuck.
In addition, all the work you do is always to improve and we must adapt and learn hand in hand with you.

2022-08-23 21:52 UTC, williamdes commented
> Hi @williamdes ....Thanks for answering.
> 
> I've edited a bit of SCSS, I'm not very familiar with it, but I think it's just a matter of studying to expand knowledge. We have to be updated as much as possible or we will be stuck. In addition, all the work you do is always to improve and we must adapt and learn hand in hand with you.

Just to be sure: do you want to update your `darkwolf` theme or create a new one ?

2022-08-23 22:04 UTC, williamdes commented
> Hi @williamdes ....Thanks for answering.
> 
> I've edited a bit of SCSS, I'm not very familiar with it, but I think it's just a matter of studying to expand knowledge. We have to be updated as much as possible or we will be stuck. In addition, all the work you do is always to improve and we must adapt and learn hand in hand with you.

Thank you for your patience !
I just added documentation, let me know how it works for you: https://github.com/phpmyadmin/themes#how-to-contribute

2022-08-23 22:26 UTC, SteppenWolf68 commented
I consider that updating the theme is the best, I hope that most of you will keep updated phpMyAdmin to the most recent version so that it works well, since from now on I will only update darkwolf for the bootstrap theme.
I really appreciate your help and patience with me.

2022-08-23 22:30 UTC, williamdes requested changes
The theme looks good and has no files that require license information.
That said I would ask two questions:
- Can this theme be re-build from it's scss files (my testing shows that no) ?
- Did you modify the `.css` file directly ?

2022-08-23 22:31 UTC, williamdes commented
> I consider that updating the theme is the best, I hope that most of you will keep updated phpMyAdmin to the most recent version so that it works well, since from now on I will only update darkwolf for the bootstrap theme. I really appreciate your help and patience with me.

Okay, so I will proceed to renaming to `darkwolf` in some of the next updates of this PR

2022-08-23 23:17 UTC, SteppenWolf68 commented
> El tema se ve bien y no tiene archivos que requieran información de licencia. Dicho esto, haría dos preguntas:
> 
> * ¿Se puede reconstruir este tema a partir de sus archivos scss (mis pruebas muestran que no)?
> * ¿Modificó el archivo directamente?`.css`

Si modifique el archivo directamente del .css

2022-08-24 08:57 UTC, williamdes commented
Okay, I think we can then update the theme and wait for your scss updates :)
Do you need some help compiling scss ?

2022-08-24 09:15 UTC, williamdes approved these changes
Did you also modify `darkwolf/css/theme.rtl.css` ?

2022-08-24 13:44 UTC, SteppenWolf68 commented
> Okay, I think we can then update the theme and wait for your scss updates :) Do you need some help compiling scss ?

For this darkwolfbootstrap theme, I would greatly appreciate your help in the scss compilation, for future versions or updates of the theme I would be doing it myself.
Really thank you very much for all your help.
Cheers

2022-10-23 14:02 UTC, merged

2022-10-23 14:53 UTC, ibennetch commented
I've uploaded this and it's now available at https://web.phpmyadmin.net/themes/#pma_5_2.

Many thanks for your contribution!